server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/springauth
        password: su123
        username: root
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create